package br.com.elotech.karina.domain;

public enum TipoAcao {

    INATIVACAO_CONTRATO,
    ATIVACAO_CONTRATO,
    ENTRADA_TITULO_FATURAMENTO,
    BAIXA_TITULO,
    TITULO_ABERTO_VENCIDO,
    PRORROGACAO_VENCIMENTO,
    ANTECIPACAO_VENCIMENTO
}
