spring:
  datasource:
    url: jdbc:jtds:sqlserver://srvFinanceiro/prototipojs
    username: prototipojs
    password: prototipojs
    driverClassName: net.sourceforge.jtds.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

liquibase:
  contexts: dev
  change-log: classpath:db/changelog/master.xml