spring:
  datasource:
    url: jdbc:jtds:sqlserver://srvFinanceiro/prototipojs
    username: prototipojs
    password: prototipojs
    driverClassName: net.sourceforge.jtds.jdbc.Driver

liquibase:
  contexts: dev
  change-log: classpath:db/changelog/master.xml